name: CI Pipeline

on:
  push:
    branches:
      - main # Altere para o nome da branch padrão do seu repositório
  pull_request:
    branches:
      - main # Altere para o nome da branch padrão do seu repositório

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m pytest tests/

      - name: Build executable
        run: |
          pyinstaller --onefile main.py # Criar executável a partir do main.py

      - name: Archive Executable
        uses: actions/upload-artifact@v2
        with:
          name: imc_executable
          path: dist/imc_app # O caminho do executável gerado pelo PyInstaller
